Creating new user after completed order
artursmet/saleor pull request #19
Opened 2016-12-19 17:05 UTC by szewczykmira

Issue #12

2016-12-20 14:42 UTC, artursmet approved these changes

2016-12-21 07:58 UTC, artursmet commented
I think there's a difference in font color on grey boxes, Isn't font color too light @weronka?

Design:
![screenshot from 2016-12-21 08-55-51](https://cloud.githubusercontent.com/assets/1754812/21381398/5998c70e-c75b-11e6-9e72-7f2d0a68a25c.png)

Site:
![image](https://cloud.githubusercontent.com/assets/1754812/21381412/7a4bb5e2-c75b-11e6-998e-a58402aacba7.png)

2016-12-21 07:58 UTC, artursmet requested changes

2016-12-21 07:58 UTC, artursmet commented on saleor/order/views.py
> +        return redirect('order:payment', token=token)
Please redirect to `order:details` page instead of order payment - this order is already paid.

2016-12-21 10:38 UTC, weronka commented
looks better I guess:

![screenshot 12](https://cloud.githubusercontent.com/assets/9913546/21386178/e5503cf8-c771-11e6-8db0-6e981e804e0f.png)

2016-12-21 10:58 UTC, artursmet approved these changes

2016-12-21 10:59 UTC, merged