Core styles for demo store
artursmet/saleor pull request #3
Opened 2016-12-02 16:17 UTC by artursmet

Re-opened pull request from main saleor repository.

2016-12-06 16:04 UTC, benekex2 requested changes

2016-12-06 16:04 UTC, benekex2 commented on saleor/static/js/demo/storefront.js
> +}
missing new line

2016-12-06 16:04 UTC, benekex2 commented on saleor/static/scss/demo/components/_breadcrumbs.scss
> +}
missing new line

2016-12-06 16:04 UTC, benekex2 commented on saleor/static/scss/demo/components/_buttons.scss
> +}
missing new line in all new scss files

2016-12-06 16:04 UTC, benekex2 commented on saleor/static/scss/demo/components/_cart-dropdown.scss
> +  padding-top: 50px;
Use $global-padding

2016-12-06 16:04 UTC, benekex2 commented on saleor/static/scss/demo/components/_footer.scss
> +    margin-top: 100px;
Use &global-margin

2016-12-06 16:04 UTC, benekex2 commented on saleor/static/scss/demo/components/_header.scss
> +      margin-right: 15px;
Use &global-margin

2016-12-06 16:04 UTC, benekex2 commented on saleor/static/scss/demo/components/_cart-dropdown.scss
> +  width: 460px;
we shouldn't use rem instead pixels ?

2016-12-06 16:04 UTC, benekex2 commented on webpack.config.js
> +  'window.Backbone': 'backbone',
We use Backbone on this project?

2016-12-06 16:08 UTC, car3oon commented on saleor/static/scss/demo/storefront.scss
> +@import "components/forms";
new line missing

2016-12-06 16:09 UTC, car3oon commented on saleor/static/scss/demo/components/_footer.scss
>  }
new line missing

2016-12-06 16:09 UTC, car3oon commented on saleor/static/scss/demo/components/_forms.scss
> +}
new line missing

2016-12-06 16:12 UTC, car3oon commented on templates/demo/cart-dropdown.html
> +    <!--
delete unused code

2016-12-06 16:58 UTC, car3oon commented on saleor/static/js/demo/storefront.js
> +});
new line missing

2016-12-06 16:58 UTC, car3oon commented on saleor/static/scss/demo/components/_cart-dropdown.scss
>  }
new line missing

2016-12-06 16:58 UTC, car3oon commented on saleor/static/js/demo/storefront.js
> +          $cartDropdown.addClass("show")
Check whole file for semicolons inconsistency

2016-12-07 10:04 UTC, artursmet commented
Is it ready to merge? @benekex2 @car3oon?

2016-12-07 11:08 UTC, merged